# Generated by Django 4.2.4 on 2023-09-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_added',
        ),
    ]
